version: "3.9"

services:
  aiaas_api_gateway_service:
    image: shuvo173/khalid_bin_arif_aiaas-api-gateway-service1.0.0
    container_name: aiaas_api_gateway_service
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - aiaas_api_gateway_service